# This is the configuration file for Ducky
# https://github.com/KoxSosen/Ducky
        token=""
        prefix=""
    [optional]
        statustype="" # Acceptable methods = PLAYING / WATCHING
        status=""
    [paste]
        pasteurl=""
    [search]
        scrapeurl=""
        proxy=""
        port=8888
        issafesearch=""
# End