# This is the configuration file for Ducky
# https://github.com/KoxSosen/Ducky
    [essential]
        token=""
        prefix=""
    [optional]
        statusmethod="" # Acceptable methods = PLAYING / STREAMING
        status="" # Not today ty
