# This is the configuration file for Ducky
# https://github.com/KoxSosen/Ducky
    [botmain]
        token=""
        prefix=""
    [optional]
        statustype="" # Acceptable methods = PLAYING / WATCHING
        status=""
    [paste]
        pasteurl=""
# End